# Project: cautious-waddle-ai
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o log.o
LINKOBJ  = main.o log.o
LIBS     = -L"D:/etc/Dev/Dev-Cpp/MinGW64/lib32" -L"D:/etc/Dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc D:/etc/Dev/Dev-Cpp/MinGW64/lib/libbgi.a -m32
INCS     = -I"D:/etc/Dev/Dev-Cpp/MinGW64/include" -I"D:/etc/Dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/etc/Dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/etc/Dev/Dev-Cpp/MinGW64/include" -I"D:/etc/Dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/etc/Dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/etc/Dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "cautious-waddle-ai .exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

log.o: log.cpp
	$(CPP) -c log.cpp -o log.o $(CXXFLAGS)
